### ISSUE TITLE
Error Importing Complex .OBJ file

### ISSUE THREAD

**Issue by julianzpe** [torontodug/DynamoModelLoader#1]
**What happened?**
Importing a complex .OBJ file returns the following:
![sandbox-error-11](https://user-images.githubusercontent.com/46332163/76097580-f5fd3780-5f95-11ea-9253-a2ed7c5f4113.PNG)
Script: [siteimport_test.dyn](https://drive.google.com/open?id=1xdyc_21N0YHITVAdshhrHtz0ZiwPK_W5)

This is how the .OBJ file looks like in Dynamo after importing with the [MeshToolkit](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Mesh-Toolkit), I'd like to use DynamoModelLoader because it can directly convert the OBJ Mesh into a PolySurface (instead of a Dynamo Mesh).

![sandbox-error-11_2](https://user-images.githubusercontent.com/46332163/76098402-5e004d80-5f97-11ea-96c9-9ff90ff2c236.PNG)

**What version of Dynamo were you using?**
Dynamo Sandbox 2.5.1 (DynamoCoreRuntime2.5.1)

**A download link for the 3D mesh file that you used (if possible, but not necessary)**
[OBJ File](https://drive.google.com/open?id=10lfdn2ZiyJDqoCmqv1QkwrzuS7ImexEw) 
[MTL File](https://drive.google.com/open?id=1XCg4br-pWcu8-pddY5bEIhZJ-dnLnHO3)

**Comment by MohsenA437** [comment]
Hi Julian,

Just wanted to let you know that I'm still actively working on this issue and am trying to figure out why its not importing correctly, though I do suppose it could be because of amount of faces in the file giving Dynamo a hard time to construct the PolySurface (Dynamo stalls in the background because of its Geometry library when I try to load the file), or it could be because of the fact that there are open faces on the mesh thus making it hard for Dynamo to figure out how to close it.

I will have to look further into the issue this upcoming week and play with the model and adjust my code a bit to ensure that it works properly, so thank you for providing a fairly complex mesh to test this project with!

-Mohsen

**Comment by julianzpe** [comment]
Hi Mohsen,

Sounds good, thanks for taking the time! In case it helps I was able to successfully import the geometry into Dynamo using the following set of functions (probably not the most efficient but it worked!):

![image](https://user-images.githubusercontent.com/46332163/76709738-8bf03b00-66d7-11ea-96e2-ef33535fefaf.png)

**Comment by julianzpe** [comment]
As can be seen in the screenshot I got some errors in **PolyCurveByPoints** for which I used remove.nulls, that's probably where your code is crashing. It's 100% the file's fault though.

**Comment by MohsenA437** [comment]
Hi Julian,

Sorry for the late reply, but I finally got a chance to figure out the issues that you pointed out.

I recently released V0.2 of this package that has support for OBJ Groups, and found out that there are issues with the model that was making it hard for my functions to convert it to Dynamo PolySurfaces. Some things to keep in mind when using an OBJ file with this package for now:

- The mesh must be triangulated
- The mesh must not have non-manifold geometry present (Edges, Vertices, or Faces that are within the mesh and are connected to outer geometry at the same time)
- The mesh is highly recommended to be a closed and water tight mesh.
- If possible with larger files, try splitting it up into smaller files to prevent Dynamo from hanging

Some of these issues such as the file size limitation are out of my control because it is how Dynamo takes care of creating geometry via external methods such as zero-touch nodes, however I will try my best to see what the absolute limit is with this package and see if I can fix as many problems as I can on my end.

Below you can see a part of your mesh that was successfully imported into Dynamo using this package:

![2020-03-20 21_20_44-Clipboard](https://user-images.githubusercontent.com/45215641/77216597-e3d0dc80-6af1-11ea-8c63-93befbc4be7f.png)

Thanks again for submitting an issue!
